/*
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JsonDslStandaloneSetup extends JsonDslStandaloneSetupGenerated{

	public static void doSetup() {
		new JsonDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

