/*
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonDslRuntimeModule extends org.xtext.dice.toscacloudifydsl.AbstractJsonDslRuntimeModule {

}
