/*
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonDslUiModule extends org.xtext.dice.toscacloudifydsl.ui.AbstractJsonDslUiModule {
	public JsonDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
