/*
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JsonDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.dice.toscacloudifydsl.ui.internal.JsonDslActivator.getInstance().getInjector("org.xtext.dice.toscacloudifydsl.JsonDsl");
	}
	
}
