/*
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JsonDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/dice/toscacloudifydsl/parser/antlr/internal/InternalJsonDsl.tokens");
	}
}
