/*
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.dice.toscacloudifydsl.ui.internal.JsonDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JsonDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JsonDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JsonDslActivator.getInstance().getInjector(JsonDslActivator.ORG_XTEXT_DICE_TOSCACLOUDIFYDSL_JSONDSL);
	}
	
}
