/**
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl.validation;

import org.xtext.dice.toscacloudifydsl.validation.AbstractJsonDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JsonDslValidator extends AbstractJsonDslValidator {
}
