/**
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl.serializer;

import org.xtext.dice.toscacloudifydsl.serializer.AbstractJsonDslSyntacticSequencer;

@SuppressWarnings("all")
public class JsonDslSyntacticSequencer extends AbstractJsonDslSyntacticSequencer {
}
