/**
 * generated by Xtext
 */
package org.xtext.dice.toscacloudifydsl.serializer;

import org.xtext.dice.toscacloudifydsl.serializer.AbstractJsonDslSemanticSequencer;

@SuppressWarnings("all")
public class JsonDslSemanticSequencer extends AbstractJsonDslSemanticSequencer {
}
